services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  mongo:
    image: mongo
    container_name: kanban-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
